version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:latest-jdk21
    container_name: codeconnectjenkins
    user: root
    ports:
      - "8500:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    entrypoint: >
      sh -c "
        apt-get update &&
        apt-get install -y git docker.io &&
        usermod -aG docker jenkins &&
        chown -R jenkins:jenkins /var/jenkins_home &&
        exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home:
