version: '3.8'

services:
  jenkins:
    image: maxin0525/nusissjenkins:v2  # 你的新 Jenkins 镜像
    container_name: nusissjenkins
    ports:
      - "8700:8080"
      - "50000:50000"
    restart: always
