services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: cdcnt_main_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - codeconnect-data:/var/lib/postgresql/data
    networks:
      - codeconnect-network

  liquibase-service:
    image: 961125mingwei/codeconnect-liquibase-service:v3
    container_name: liquibase-service
    environment:
      POSTGRES_DB: cdcnt_main_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres-db
    ports:
      - "8081:8081"
    networks:
      - codeconnect-network

  user-management-service:
    image: 961125mingwei/codeconnect-user-management-service:v3
    container_name: user-management-service
    ports:
      - "8082:8082"
    networks:
      - codeconnect-network
    depends_on:
      - liquibase-service
    environment:
      - SPRING_PROFILES_ACTIVE=uat

  admin-management-service:
    image: 961125mingwei/codeconnect-admin-management-service:v3
    container_name: admin-management-service
    ports:
      - "8083:8083"
    networks:
      - codeconnect-network
    depends_on:
      - liquibase-service
    environment:
      - SPRING_PROFILES_ACTIVE=uat

  job-management-service:
    image: 961125mingwei/codeconnect-job-management-service:v3
    container_name: job-management-service
    ports:
      - "8084:8084"
    networks:
      - codeconnect-network
    depends_on:
      - liquibase-service
    environment:
      - SPRING_PROFILES_ACTIVE=uat

  interview-prep-service:
    image: 961125mingwei/codeconnect-interview-prep-service:v3
    container_name: interview-prep-service
    ports:
      - "8085:8085"
    networks:
      - codeconnect-network
    depends_on:
      - liquibase-service
    environment:
      - SPRING_PROFILES_ACTIVE=uat

  api-gateway:
    image: 961125mingwei/codeconnect-api-gateway:v3
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - codeconnect-network
    depends_on:
      - liquibase-service
      - admin-management-service
      - job-management-service
      - interview-prep-service
      - user-management-service
    environment:
      - SPRING_PROFILES_ACTIVE=uat

  app-frontend:
    image: jonathantayyw/code-connect-frontend:latest
    container_name: app-frontend
    ports:
      - "3000:3000"
    networks:
      - codeconnect-network
    depends_on:
      - api-gateway

networks:
  codeconnect-network:
    driver: bridge

volumes:
  codeconnect-data:
