server:
  port: 8083

# Custom properties
cdcnt:
  services:
    user-service:
      url: http://localhost:8082/api/v1
      get-all-employer-profiles: /list-employer-profiles
      review-employer-profiles: /review-employer-profiles
      delete-employer-profiles: /employer-profiles
      get-all-employee-profiles: /list-employee-profiles

    job-service:
      url: http://localhost:8084/api/v1
      review-job-posting: /jobpostings/review