server:
  port: 8083

# Custom properties
cdcnt:
  services:
    user-service:
      url: http://localhost:8082
      get-all-employer-profiles: /employer-profiles
      review-employer-profiles: /review-employer-profiles
      delete-employer-profiles: /employer-profiles

    job-service:
      url: http://localhost:8083